### ISSUE TITLE
驱动支持

### ISSUE THREAD

**Issue by zfdx123** [wu17481748/UFI-Ubuntu20.40#1]
尊敬的开发者您好，请问有没有移植文档，我想要定制一个Ubuntu使用，谢谢

**Comment by wu17481748** [comment]
https://www.kancloud.cn/handsomehacker/openstick/2637565
参考次文档编译debian过程！替换rootfs为ubuntu.20.04的更改UUID为ubuntu.20.04系统ubuntu.img的！(ubuntu.img=rootfs.img)

**Comment by zfdx123** [comment]
收到，谢谢您

**Comment by zfdx123** [comment]
我刚从ubuntu-base移植，编译安装了内核，发现没有生成initrd，请问这个文件要怎样生成

**Comment by Bugday001** [comment]
> 我刚从ubuntu-base移植，编译安装了内核，发现没有生成initrd，请问这个文件要怎样生成

不知道你有没有找到原因，我发现是因为没有安装`update-initramfs`，安装后就会自动生成了。
